#!/bin/bash

if [ "$1" = "help" ]
then
    echo "Vipir"
    echo
    echo "Commands:"
    echo
    echo "setup        Setup a virtual environment."
    echo "install      Install a package."
    echo "uninstall    Uninstall a package."
    echo "env          Enter/Leave the virtual environment."
    echo "graph        Show installed packages."
    echo "freeze       Freeze installed packages."
    echo "require      Install required packages specified in ./requirements.txt."

elif [ "$1" = "setup" ]
then
    VIPIR=.vipir/
    if [ -d "$VIPIR" ]
    then
        echo "There is already a virtual environment setup in this project."
    else
        PROJECT=$(basename "$PWD")
        echo "Creating a virtual environment..."
        virtualenv ".vipir/$PROJECT"

        if [ -f ".gitignore" ]
        then
            echo ".vipir" >> .gitignore
        fi
    fi

elif [ "$1" = "install" ]
then
    VIPIR=.vipir/
    if [ -d "$VIPIR" ]
    then
        if [ ! -z "$VIRTUAL_ENV" ]
        then
            for var in "$@"
            do
                if [[ "$var" != "$0" && "$var" != "$1" ]]
                then
                    pip3 install "$var"
                fi
            done
        fi
    else
        echo "There is no virtual environment setup in this project."
    fi

elif [ "$1" = "uninstall" ]
then
    VIPIR=.vipir/
    if [ -d "$VIPIR" ]
    then
        if [ ! -z "$VIRTUAL_ENV" ]
        then
            for var in "$@"
            do
                if [[ "$var" != "$0" && "$var" != "$1" ]]
                then
                    pip3 uninstall "$var"
                fi
            done
        else
            echo "Enter the virtual environment to uninstall packages."
        fi
    else
        echo "There is no virtual environment setup in this project."
    fi

elif [ "$1" = "env" ]
then
    VIPIR=.vipir/
    if [ -z "$VIRTUAL_ENV" ]
    then
        if [ -d "$VIPIR" ]
        then
            PROJECT=$(basename "$PWD")
            source ./.vipir/$PROJECT/bin/activate
        else
            echo "There is no virtual environment setup in this project."
        fi
    else
        deactivate
    fi

elif [ "$1" = "graph" ]
then
    VIPIR=.vipir/
    if [ -d "$VIPIR" ]
    then
        if [ ! -z "$VIRTUAL_ENV" ]
        then
            pip3 list
        else
            echo "Enter the virtual environment to list packages."
        fi
    else
        echo "There is no virtual environment setup in this project."
    fi

elif [ "$1" = "freeze" ]
then
    VIPIR=.vipir/
    if [ -d "$VIPIR" ]
    then
        if [ ! -z "$VIRTUAL_ENV" ]
        then
            pip3 freeze > requirements.txt
        else
            echo "Enter the virtual environment to freeze packages."
        fi
    else
        echo "There is no virtual environment setup in this project."
    fi

elif [ "$1" = "require" ]
then
    VIPIR=.vipir/
    if [ -d "$VIPIR" ]
    then
        if [ -f "requirements.txt" ]
        then
            if [ ! -z "$VIRTUAL_ENV" ]
            then
                pip3 install -r requirements.txt
            else
                echo "Enter the virtual environment to installed required packages."
            fi
        else
            echo "No requirements found."
        fi
    else
        echo "There is no virtual environment setup in this project."
    fi

else
    echo "Command unknown type 'vipir help' for help."

fi
